version: '3.8'

services:
  infycal_app:
    build:
      context: /root/xcal/xcal
      dockerfile: Dockerfile
    image: infycal_app_image
    container_name: infycal_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - /root/xcal/xcal/src:/var/www/html
    networks:
      - infycal_net

  infycal_nginx:
    image: nginx:alpine
    container_name: infycal_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - /root/xcal/xcal/src:/var/www/html
      - /root/xcal/xcal/nginx:/etc/nginx/conf.d
    depends_on:
      - infycal_app
    networks:
      - infycal_net

  infycal_db:
    image: mysql:5.7
    container_name: infycal_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    volumes:
      - infycal_db_data:/var/lib/mysql
    networks:
      - infycal_net

volumes:
  infycal_db_data:

networks:
  infycal_net:
    driver: bridge
